config: !Configuration
  vdos:
    QBOP0B00S02: !VDOService
      _operationState: finished
      ackThreads: 2
      activated: enabled
      bioRotationInterval: 64
      bioThreads: 2
      blockMapCacheSize: 512M
      blockMapPeriod: 16380
      compression: enabled
      cpuThreads: 16
      deduplication: disabled
      device: /dev/qdisk/P0B00S02
      hashZoneThreads: 2
      indexCfreq: 0
      indexMemory: 0.25
      indexSparse: disabled
      indexThreads: 0
      logicalBlockSize: 512
      logicalSize: 800G
      logicalThreads: 4
      name: QBOP0B00S02
      physicalSize: 372G
      physicalThreads: 4
      readCache: enabled
      readCacheSize: 512M
      slabSize: 2G
      writePolicy: async
    QBOP0B00S03: !VDOService
      _operationState: finished
      ackThreads: 2
      activated: enabled
      bioRotationInterval: 64
      bioThreads: 2
      blockMapCacheSize: 512M
      blockMapPeriod: 16380
      compression: enabled
      cpuThreads: 16
      deduplication: disabled
      device: /dev/qdisk/P0B00S03
      hashZoneThreads: 2
      indexCfreq: 0
      indexMemory: 0.25
      indexSparse: disabled
      indexThreads: 0
      logicalBlockSize: 512
      logicalSize: 800G
      logicalThreads: 4
      name: QBOP0B00S03
      physicalSize: 372G
      physicalThreads: 4
      readCache: enabled
      readCacheSize: 512M
      slabSize: 2G
      writePolicy: async
    QBOP0B00S04: !VDOService
      _operationState: finished
      ackThreads: 2
      activated: enabled
      bioRotationInterval: 64
      bioThreads: 2
      blockMapCacheSize: 512M
      blockMapPeriod: 16380
      compression: enabled
      cpuThreads: 16
      deduplication: disabled
      device: /dev/qdisk/P0B00S04
      hashZoneThreads: 2
      indexCfreq: 0
      indexMemory: 0.25
      indexSparse: disabled
      indexThreads: 0
      logicalBlockSize: 512
      logicalSize: 800G
      logicalThreads: 4
      name: QBOP0B00S04
      physicalSize: 372G
      physicalThreads: 4
      readCache: enabled
      readCacheSize: 512M
      slabSize: 2G
      writePolicy: async
    QBOP0B00S05: !VDOService
      _operationState: finished
      ackThreads: 2
      activated: enabled
      bioRotationInterval: 64
      bioThreads: 2
      blockMapCacheSize: 512M
      blockMapPeriod: 16380
      compression: enabled
      cpuThreads: 16
      deduplication: disabled
      device: /dev/qdisk/P0B00S05
      hashZoneThreads: 2
      indexCfreq: 0
      indexMemory: 0.25
      indexSparse: disabled
      indexThreads: 0
      logicalBlockSize: 512
      logicalSize: 800G
      logicalThreads: 4
      name: QBOP0B00S05
      physicalSize: 372G
      physicalThreads: 4
      readCache: enabled
      readCacheSize: 512M
      slabSize: 2G
      writePolicy: async
    QBOP0B00S08: !VDOService
      _operationState: finished
      ackThreads: 2
      activated: enabled
      bioRotationInterval: 64
      bioThreads: 2
      blockMapCacheSize: 512M
      blockMapPeriod: 16380
      compression: enabled
      cpuThreads: 16
      deduplication: disabled
      device: /dev/qdisk/P0B00S08
      hashZoneThreads: 2
      indexCfreq: 0
      indexMemory: 0.25
      indexSparse: disabled
      indexThreads: 0
      logicalBlockSize: 512
      logicalSize: 800G
      logicalThreads: 4
      name: QBOP0B00S08
      physicalSize: 372G
      physicalThreads: 4
      readCache: enabled
      readCacheSize: 512M
      slabSize: 2G
      writePolicy: async
  version: 538380551
filename: /etc/vdoconf.yml

